### ISSUE TITLE
Failed to mount deployment

### ISSUE THREAD

**Issue by mcheriyath** [goldmann/wildfly-docker-deployment-example#2]
Can you please let me know what I might be missing here.

Followed the same steps added the war to a Dockerfile build and ran the container, but throwing:
Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: JBAS018740: Failed to mount deployment content

**Comment by cadmy** [comment]
Same issue:
Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: JBAS018740: Failed to mount deployment content
Caused by: java.io.FileNotFoundException: /opt/jboss/wildfly/standalone/deployments/game.war (Permission denied)"}}

**Comment by Olatunji-Longe** [comment]
Experiencing Similar issue on wildfly9.0.1, even though app.war has been renamed and doesn't exist anymore in context

Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: WFLYSRV0160: 

Failed to mount deployment content
	at org.jboss.as.server.deployment.module.DeploymentRootMountProcessor.deploy(DeploymentRootMountProcessor.java:95)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:156)
	... 5 more
Caused by: java.io.FileNotFoundException: C:\user-home\project\target\app.war (The system cannot find the file specified)

**Comment by eniniz** [comment]
+1
